const avatarUrl =
  'https://buffer-uploads.s3.amazonaws.com/503a5c8ffc99f72a7f00002e/f49c2ff693f1c307af5e1b3d84e581ca.png';

export const selectedProfile = {
  id: '1234',
  avatarUrl,
  service: 'twitter',
  type: 'twitter',
  handle: 'joelgascoigne',
  isManager: true,
  open: false,
  schedules: [],
  loading: false,
  loadingMore: false,
  moreToLoad: false,
  page: 1,
  posts: {},
  total: 0,
};

export const profiles = [
  selectedProfile,
  {
    id: '1235',
    avatarUrl,
    service: 'facebook',
    type: 'facebook',
    handle: 'Joel Gascoigne',
    notifications: 1,
    disabled: true,
    open: false,
    schedules: [],
    loading: false,
    loadingMore: false,
    moreToLoad: false,
    page: 1,
    posts: {},
    total: 0,
  },
  {
    id: '1236',
    avatarUrl,
    service: 'twitter',
    type: 'twitter',
    handle: 'buffer',
    notifications: 1,
    disabled: false,
    open: false,
    schedules: [],
    loading: false,
    loadingMore: false,
    moreToLoad: false,
    page: 1,
    posts: {},
    total: 0,
  },
  {
    id: '1237',
    avatarUrl,
    service: 'twitter',
    type: 'twitter',
    handle: 'buffer',
    notifications: 1,
    disabled: false,
    open: false,
    schedules: [],
    loading: false,
    loadingMore: false,
    moreToLoad: false,
    page: 1,
    posts: {},
    total: 0,
  },
  {
    id: '1238',
    avatarUrl,
    service: 'twitter',
    type: 'twitter',
    handle: 'buffer',
    notifications: 1,
    disabled: false,
    open: false,
    schedules: [],
    loading: false,
    loadingMore: false,
    moreToLoad: false,
    page: 1,
    posts: {},
    total: 0,
  },
  {
    id: '1239',
    avatarUrl,
    service: 'twitter',
    type: 'twitter',
    handle: 'buffer',
    notifications: 1,
    disabled: false,
    open: false,
    schedules: [],
    loading: false,
    loadingMore: false,
    moreToLoad: false,
    page: 1,
    posts: {},
    total: 0,
  },
];
