module.exports = orgData => ({
  id: orgData.id,
  globalOrgId: orgData.global_organization_id,
  locked: orgData.locked,
  selected: orgData.selected,
  name: orgData.name,
  ownerId: orgData.owner_id,
  ownerEmail: orgData.owner_email,
  ownerFeatures: orgData.ownerFeatures,
  plan: orgData.plan_name,
  planBase: orgData.planBase,
  planCode: orgData.plan_code,
  isNonProfit: orgData.isNonProfit,
  profileLimit: orgData.profileLimit,
  profilesCount: orgData.profilesCount,
  usersCount: orgData.usersCount,
  isAdmin: orgData.is_admin,
});
