module.exports = orgData => ({
  id: orgData.id,
  globalOrgId: orgData.global_organization_id || orgData.globalOrgId,
  locked: orgData.locked,
  selected: orgData.selected,
  name: orgData.name,
  ownerId: orgData.owner_id || orgData.ownerId,
  ownerEmail: orgData.owner_email || orgData.ownerEmail,
  ownerFeatures: orgData.ownerFeatures,
  plan: orgData.plan_name || orgData.planName,
  planBase: orgData.planBase,
  planCode: orgData.plan_code || orgData.planCode,
  isNonProfit: orgData.isNonProfit,
  profileLimit: orgData.profileLimit,
  profilesCount: orgData.profilesCount,
  usersCount: orgData.usersCount,
  isAdmin: orgData.is_admin || orgData.isAdmin,
  isOwner: orgData.is_owner || orgData.isOwner,
});
